name: 🐛 Bug Report
description: File a bug report to help us improve
title: '[BUG]: '
labels: ['bug', 'triage']
body:
  - type: markdown
    attributes:
      value: |
        # 🐛 Bug Report

        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

        **Before submitting**: Please search existing issues to avoid duplicates.

  - type: input
    id: related-issues
    attributes:
      label: Related Issues
      description: Link any related issues or PRs (use "None" if no related issues)
      placeholder: '#123, #456, or None'
    validations:
      required: true

  - type: input
    id: error-keywords
    attributes:
      label: Error Keywords
      description: Key error messages or keywords (helps find duplicates)
      placeholder: 'Cannot find module, TypeError, 404 Unauthorized, etc.'
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction Steps
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: Drag and drop screenshots here...

  - type: dropdown
    id: application-area
    attributes:
      label: Application Area
      description: Which part of the application is affected?
      options:
        - Web Frontend (Astro)
        - API Backend (NestJS)
        - Database
        - Authentication
        - File Management
        - Client Portal
        - Admin Panel
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical - Blocks core functionality
        - High - Major functionality broken
        - Medium - Some functionality affected
        - Low - Minor issue or cosmetic
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: What environment are you running this in?
      placeholder: e.g., Production, Staging, Development
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information...

  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      description: Please confirm the following
      options:
        - label: 'I have searched existing issues for similar problems (checked keywords: [error keywords from above])'
          required: true
        - label: I have provided enough information to reproduce the issue
          required: true
        - label: I have checked the troubleshooting documentation
        - label: This issue is not a duplicate of any existing issue
          required: true
