name: ✨ Feature Request
description: Suggest an idea for this project
title: "[FEATURE]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        # ✨ Feature Request
        
        Thanks for suggesting a new feature! Please provide as much detail as possible.
        
        **Before submitting**: Please search existing issues to avoid duplicate feature requests.

  - type: input
    id: related-issues
    attributes:
      label: Related Issues
      description: Link any related issues or PRs (use "None" if no related issues)
      placeholder: "#123, #456, or None"
    validations:
      required: true

  - type: input
    id: feature-keywords
    attributes:
      label: Feature Keywords
      description: Key terms that describe this feature (helps find duplicates)
      placeholder: "authentication, dashboard, export, API, etc."
    validations:
      required: true

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What pain point does it address?
      placeholder: Explain the problem this feature would solve...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How do you envision this feature working?
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternative approaches...

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New Functionality
        - Enhancement to Existing Feature
        - UI/UX Improvement
        - Performance Improvement
        - Security Enhancement
        - Integration
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Critical - Must have for MVP
        - High - Important for next release
        - Medium - Nice to have
        - Low - Future consideration
    validations:
      required: true

  - type: dropdown
    id: target-area
    attributes:
      label: Target Area
      description: Which part of the application would this affect?
      options:
        - Web Frontend (Astro)
        - API Backend (NestJS)
        - Database Schema
        - Authentication System
        - File Management
        - Client Portal
        - Admin Panel
        - Infrastructure/DevOps
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What would make this feature complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: If applicable, add mockups, screenshots, or examples
      placeholder: Drag and drop images or provide links...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here
      placeholder: Any additional information...

  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      description: Please confirm the following
      options:
        - label: I have searched existing issues for similar requests (checked keywords: [feature keywords from above])
          required: true
        - label: I have read the project documentation and roadmap
          required: true
        - label: This feature aligns with the project goals
          required: true
        - label: This is not a duplicate of any existing feature request
          required: true