name: 🚀 Release
description: Track release preparation and deployment
title: "[RELEASE]: v"
labels: ["release", "deployment"]
body:
  - type: markdown
    attributes:
      value: |
        Use this template to track release preparation and deployment activities.

  - type: input
    id: version
    attributes:
      label: Version
      description: Semantic version number (e.g., 1.2.3)
      placeholder: 1.0.0
    validations:
      required: true

  - type: dropdown
    id: release-type
    attributes:
      label: Release Type
      description: What type of release is this?
      options:
        - Major - Breaking changes
        - Minor - New features
        - Patch - Bug fixes
        - Pre-release - Alpha/Beta/RC
    validations:
      required: true

  - type: textarea
    id: release-summary
    attributes:
      label: Release Summary
      description: Brief summary of what's included in this release
      placeholder: Summarize the release...
    validations:
      required: true

  - type: textarea
    id: features
    attributes:
      label: New Features
      description: List of new features in this release
      placeholder: |
        - Feature 1 (#123)
        - Feature 2 (#124)

  - type: textarea
    id: bug-fixes
    attributes:
      label: Bug Fixes
      description: List of bug fixes in this release
      placeholder: |
        - Fixed issue 1 (#125)
        - Fixed issue 2 (#126)

  - type: textarea
    id: improvements
    attributes:
      label: Improvements
      description: List of improvements and optimizations
      placeholder: |
        - Performance improvement 1
        - Code quality improvement 2

  - type: textarea
    id: breaking-changes
    attributes:
      label: Breaking Changes
      description: List any breaking changes and migration instructions
      placeholder: Describe breaking changes and how to migrate...

  - type: textarea
    id: security-updates
    attributes:
      label: Security Updates
      description: List any security-related updates
      placeholder: Describe security updates...

  - type: dropdown
    id: deployment-target
    attributes:
      label: Deployment Target
      description: Where will this be deployed?
      options:
        - Production
        - Staging
        - Development
        - All environments
    validations:
      required: true

  - type: checkboxes
    id: pre-release-checklist
    attributes:
      label: Pre-Release Checklist
      description: Complete all items before release
      options:
        - label: All tests passing
          required: true
        - label: Documentation updated
          required: true
        - label: CHANGELOG updated
          required: true
        - label: Version numbers updated
          required: true
        - label: Security scan passed
          required: true
        - label: Performance tests passed (if applicable)
        - label: Stakeholder approval received
        - label: Rollback plan prepared

  - type: checkboxes
    id: post-release-checklist
    attributes:
      label: Post-Release Checklist
      description: Complete after deployment
      options:
        - label: Deployment successful
        - label: Health checks passing
        - label: Monitoring alerts configured
        - label: Release notes published
        - label: Team notified
        - label: User communication sent (if needed)

  - type: textarea
    id: rollback-plan
    attributes:
      label: Rollback Plan
      description: How to rollback if something goes wrong
      placeholder: Describe the rollback procedure...

  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      description: Any other important information
      placeholder: Additional notes...