name: 🔧 Technical Task
description: Create a technical task for implementation work
title: "[TASK]: "
labels: ["technical-task", "implementation"]
body:
  - type: markdown
    attributes:
      value: |
        # 🔧 Technical Task
        
        Use this template for technical implementation tasks that don't fit bug reports or feature requests.
        
        **Before submitting**: Please search existing issues to avoid duplicate tasks.

  - type: input
    id: related-issues
    attributes:
      label: Related Issues
      description: Link any related issues or PRs (use "None" if no related issues)
      placeholder: "#123, #456, or None"
    validations:
      required: true

  - type: input
    id: task-keywords
    attributes:
      label: Task Keywords
      description: Key terms that describe this technical task (helps find duplicates)
      placeholder: "refactoring, optimization, migration, testing, etc."
    validations:
      required: true

  - type: textarea
    id: task-description
    attributes:
      label: Task Description
      description: Clear description of what needs to be done
      placeholder: Describe the technical task...
    validations:
      required: true

  - type: dropdown
    id: task-type
    attributes:
      label: Task Type
      description: What type of technical task is this?
      options:
        - Refactoring
        - Performance Optimization
        - Security Enhancement
        - Testing
        - Documentation
        - Infrastructure/DevOps
        - Code Quality
        - Dependency Update
        - Other
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component/Area
      description: Which part of the codebase does this affect?
      options:
        - Web Frontend (Astro)
        - API Backend (NestJS)
        - Database
        - Authentication
        - File Management
        - Client Portal
        - Admin Panel
        - Shared Packages
        - CI/CD
        - Other
    validations:
      required: true

  - type: textarea
    id: technical-requirements
    attributes:
      label: Technical Requirements
      description: Specific technical requirements or constraints
      placeholder: List technical requirements...

  - type: textarea
    id: implementation-steps
    attributes:
      label: Implementation Steps
      description: Step-by-step plan for implementation
      placeholder: |
        1. Step one
        2. Step two
        3. Step three

  - type: textarea
    id: testing-requirements
    attributes:
      label: Testing Requirements
      description: What testing needs to be done?
      placeholder: Describe testing requirements...

  - type: dropdown
    id: complexity
    attributes:
      label: Complexity
      description: How complex is this task?
      options:
        - Simple - Few hours
        - Medium - 1-2 days
        - Complex - 3-5 days
        - Very Complex - More than a week
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this task?
      options:
        - Urgent - Blocker
        - High - Priority for current sprint
        - Medium - Can wait for next sprint
        - Low - Backlog
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: Are there any dependencies or blockers?
      placeholder: List any dependencies...

- type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      description: Please confirm the following
      options:
        - label: I have searched existing issues for similar technical tasks (checked keywords: [task keywords from above])
          required: true
        - label: I have reviewed the technical requirements thoroughly
          required: true
        - label: This is not a duplicate of any existing task
          required: true

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
    description: Any additional information or context
    placeholder: Additional notes...