
import { readFile, writeFile } from 'fs/promises';
import path from 'path';

interface HealthReport {
    timestamp: string;
    commitHash: string;
    status: 'passing' | 'warning' | 'critical';
    metrics: {
        typecheck: { status: 'pass' | 'fail'; time: number };
        lint: { status: 'pass' | 'fail'; time: number; errors: number; warnings: number };
        test: { status: 'pass' | 'fail'; time: number; total: number; failed: number };
        build: { status: 'pass' | 'fail'; time: number; bundleSize: string; gzipSize: string };
        performance: { score: number; grade: string };
    };
    issues: string[]; // Critical issues only
    recommendations: string[];
}

async function generateReport() {
    // Mock data collection - in real workflow workflow inputs/env vars would populate this
    // This script is intended to be run by the CI workflow which will inject values via ENV

    const env = process.env;

    const report: HealthReport = {
        timestamp: new Date().toISOString(),
        commitHash: env.GITHUB_SHA || 'unknown',
        status: (env.CHECKS_FAILED === 'true') ? 'critical' : 'passing',
        metrics: {
            typecheck: {
                status: env.TYPECHECK_STATUS === 'failure' ? 'fail' : 'pass',
                time: Number(env.TYPECHECK_TIME || 0)
            },
            lint: {
                status: env.LINT_STATUS === 'failure' ? 'fail' : 'pass',
                time: Number(env.LINT_TIME || 0),
                errors: Number(env.LINT_ERRORS || 0),
                warnings: Number(env.LINT_WARNINGS || 0)
            },
            test: {
                status: env.TEST_STATUS === 'failure' ? 'fail' : 'pass',
                time: Number(env.TEST_TIME || 0),
                total: Number(env.TEST_COUNT || 0),
                failed: Number(env.TEST_FAILED || 0)
            },
            build: {
                status: env.BUILD_STATUS === 'failure' ? 'fail' : 'pass',
                time: Number(env.BUILD_TIME || 0),
                bundleSize: env.BUNDLE_SIZE || '0KB',
                gzipSize: env.GZIP_SIZE || '0KB'
            },
            performance: {
                score: Number(env.PERF_SCORE || 0),
                grade: env.PERF_GRADE || 'N/A'
            }
        },
        issues: [],
        recommendations: []
    };

    // Populate Issues logic
    if (report.metrics.lint.errors > 0) report.issues.push(`Linting failed with ${report.metrics.lint.errors} errors`);
    if (report.metrics.test.failed > 0) report.issues.push(`Test suite failed with ${report.metrics.test.failed} regressions`);
    if (parseInt(report.metrics.build.bundleSize) > 250) report.issues.push(`Critical: Bundle size (${report.metrics.build.bundleSize}) exceeds 250KB limit`);

    // Performance Analysis Logic integration
    if (parseInt(report.metrics.build.bundleSize) > 200) report.recommendations.push("Optimize bundle size (approaching 250KB limit)");
    if (report.metrics.performance.score < 85) report.recommendations.push("Improve performance score (below 85)");

    const markdown = `# System Health Report
> **Auto-Generated by CI** | ${report.timestamp} | Commit: \`${report.commitHash.substring(0, 7)}\`

## 📊 Quick Status: ${report.status === 'passing' ? '🟢 PASSING' : '🔴 CRITICAL'}

| Metric | Status | Details | Time |
|--------|--------|---------|------|
| **TypeCheck** | ${report.metrics.typecheck.status === 'pass' ? '✅' : '❌'} | Strict Mode | ${report.metrics.typecheck.time}s |
| **Lint** | ${report.metrics.lint.status === 'pass' ? '✅' : '❌'} | ${report.metrics.lint.errors} err, ${report.metrics.lint.warnings} warn | ${report.metrics.lint.time}s |
| **Test** | ${report.metrics.test.status === 'pass' ? '✅' : '❌'} | ${report.metrics.test.total} tests (${report.metrics.test.failed} fail) | ${report.metrics.test.time}s |
| **Build** | ${report.metrics.build.status === 'pass' ? '✅' : '❌'} | ${report.metrics.build.bundleSize} (gzip: ${report.metrics.build.gzipSize}) | ${report.metrics.build.time}s |
| **Perf** | ${report.metrics.performance.score >= 80 ? '✅' : '⚠️'} | Score: ${report.metrics.performance.score}/100 (Grade: ${report.metrics.performance.grade}) | - |

## 🚨 Critical Action Items
${report.issues.length > 0 ? report.issues.map(i => `- 🔴 **${i}**`).join('\n') : '- ✅ System is healthy. No critical issues detected.'}

## 💡 Performance Recommendations
${report.recommendations.length > 0 ? report.recommendations.map(r => `- ⚡ ${r}`).join('\n') : '- ✨ No immediate optimizations required.'}
`;

    await writeFile(path.join(process.cwd(), 'docs/system-health.md'), markdown);
    console.log('Report generated at docs/system-health.md');
}

generateReport().catch(console.error);
